PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TB_EXPORT" (

  "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,

  "ALTERNATIVE" TEXT NOT NULL,

  "ISCHOOSE" integer NOT NULL DEFAULT 0,

  "BYNAME" TEXT

);
INSERT INTO TB_EXPORT VALUES(1,'PipeCode',1,'管道编号');
INSERT INTO TB_EXPORT VALUES(2,'PipeType',1,'管道类型');
INSERT INTO TB_EXPORT VALUES(3,'TaskCode',1,'任务编号');
INSERT INTO TB_EXPORT VALUES(4,'Address',1,'地址');
INSERT INTO TB_EXPORT VALUES(5,'Charge',1,'负责人');
INSERT INTO TB_EXPORT VALUES(6,'StartTime',1,'开始时间');
INSERT INTO TB_EXPORT VALUES(7,'EndTime',1,'结束时间');
INSERT INTO TB_EXPORT VALUES(8,'Position',1,'异常帧帧号');
INSERT INTO TB_EXPORT VALUES(9,'Type',1,'是否异常');
CREATE TABLE IF NOT EXISTS "TB_MODEL" (

  "ID" INTEGER NOT NULL,

  "MODELNAME" TEXT NOT NULL,

  "CREATETIME" TEXT NOT NULL,

  "LOCATION" TEXT NOT NULL,

  "UPDATETIME" TEXT,

  "SIMPLE" TEXT,

  "RATE" integer DEFAULT 95,

  "LTERATION" integer DEFAULT 5000,

  PRIMARY KEY ("ID")

);
CREATE TABLE IF NOT EXISTS "TB_ABNORMALLIST" (

  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,

  "CATEGORY" TEXT NOT NULL,

  "TYPE" integer NOT NULL,

  "NAME" TEXT NOT NULL

);
INSERT INTO TB_ABNORMALLIST VALUES(1,'良好',0,'良好');
INSERT INTO TB_ABNORMALLIST VALUES(2,'结构性缺陷',1,'破裂');
INSERT INTO TB_ABNORMALLIST VALUES(3,'结构性缺陷',2,'腐蚀');
INSERT INTO TB_ABNORMALLIST VALUES(4,'功能性缺陷',3,'树根');
INSERT INTO TB_ABNORMALLIST VALUES(5,'功能性缺陷',4,'结垢');
INSERT INTO TB_ABNORMALLIST VALUES(6,'未定义',5,'未定义');
INSERT INTO TB_ABNORMALLIST VALUES(7,'良好',6,'良好');
INSERT INTO TB_ABNORMALLIST VALUES(8,'功能性缺陷',7,'障碍物');
INSERT INTO TB_ABNORMALLIST VALUES(9,'结构性缺陷',8,'起伏');
INSERT INTO TB_ABNORMALLIST VALUES(10,'功能性缺陷',9,'沉积');
INSERT INTO TB_ABNORMALLIST VALUES(11,'结构性缺陷',10,'错口');
INSERT INTO TB_ABNORMALLIST VALUES(12,'功能性缺陷',11,'浮渣');
INSERT INTO TB_ABNORMALLIST VALUES(13,'结构性缺陷',12,'脱节');
INSERT INTO TB_ABNORMALLIST VALUES(14,'结构性缺陷',13,'接口材料脱落');
INSERT INTO TB_ABNORMALLIST VALUES(15,'结构性缺陷',14,'支管暗接');
INSERT INTO TB_ABNORMALLIST VALUES(16,'结构性缺陷',15,'异物穿入');
INSERT INTO TB_ABNORMALLIST VALUES(17,'结构性缺陷',16,'渗漏');
INSERT INTO TB_ABNORMALLIST VALUES(18,'功能性缺陷',17,'残墙坝根');
INSERT INTO TB_ABNORMALLIST VALUES(19,'结构性缺陷',18,'变形');
ANALYZE sqlite_master;
INSERT INTO sqlite_stat1 VALUES('TB_ABNORMAL',NULL,'8');
CREATE TABLE IF NOT EXISTS "TB_METADATA" (

  "ID" integer NOT NULL PRIMARY KEY AUTOINCREMENT,

  "PIPECODE" TEXT NOT NULL,

  "PIPETYPE" integer NOT NULL,

  "TASKCODE" TEXT NOT NULL,

  "ADDR" TEXT NOT NULL,

  "CHARGE" TEXT NOT NULL,

  "STARTTIME" TEXT,

  "VIDEOPATH" TEXT NOT NULL,

  "INTERVAL" integer DEFAULT 25,

  "FRAMEPATH" TEXT,

  "HEADTIME" TEXT,

  "TAILTIME" TEXT,

  "SFZD" integer,

  "GXDDH" text,

  "GXDGS" integer,

  "GC" TEXT,

  "GJ" real,

  "JCFX" integer,

  "GXC" real,

  "QSMS" real,

  "ZZMS" real

);
CREATE TABLE IF NOT EXISTS "TB_ABNORMAL" (

  "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,

  "VIDEOID" integer NOT NULL,

  "POSITION" TEXT NOT NULL,

  "TYPE" integer NOT NULL DEFAULT 0,

  "QPWZ" TEXT,

  "QXWZ" real,

  "DJ" integer,

  "SZBS" TEXT,

  "BZ" TEXT,

  "SFXF" TEXT,

  "MS" TEXT,

  "TPMC" TEXT

);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('TB_EXPORT',9);
INSERT INTO sqlite_sequence VALUES('TB_ABNORMALLIST',19);
INSERT INTO sqlite_sequence VALUES('TB_METADATA',69);
INSERT INTO sqlite_sequence VALUES('TB_ABNORMAL',164);
COMMIT;
